[platformio]
default_envs = esp32dev

[env]
test_framework = unity

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  robtillaart/MAX6675 @ ^0.3.1
  bblanchon/ArduinoJson @ ^7.0.4
  tzapu/WiFiManager @ ^2.0.17

[env:native]
platform = native
test_build_src = false
